### PR TITLE
LilyGO T-Deck support board

### PR DESCRIPTION
**Pull request by hpsaturn**
## Summary

This PR try to include support for the T-Deck board

## TODO

- [x] new environment
- [x] added board definition from LilyGO 
- [x] mock definitions copied from MakerFabs 
- [x] compiling with mock pins and new env
- [x] migrate to the right pins
- [x] added test workflow for TDeck 
- [x] validate LGFX setup
- [x] validate LVGL setup
- [ ] SD card issue
- [x] Touch i2c issue

## References

 Seems that the board uses these pins:
 https://github.com/moononournation/T-Deck/blob/main/LvglWidgets_VGA/TDECK_PINS.h
 LilyGO uses this for TFTeSPI library:
 https://github.com/Xinyuan-LilyGO/T-Deck/blob/master/lib/TFT_eSPI/User_Setups/Setup210_LilyGo_T_Deck.h

### CODE REVIEW

**Comment by jgauchia** [comment]
Hi.
See this link:
https://github.com/espressif/esp-idf/issues/12843

Maybe is a problem with arduino framework version?

**Comment by jgauchia** [comment]
Hi, I've updated hal.hpp and panel definition in order to match TDECK, 
Please review attached comments about GPIO definition (in hal.hpp) and i2c addres for touch (in panel file)

**Comment by hpsaturn** [comment]
Well, thanks, with the last changes around the TFT header, is compiling ok without linking issues. The next issue is someone with the SD:

```cpp
[  1852][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[  1858][V][settings.cpp:317] printSettings():    Web_file      default 

assert failed: xQueueSemaphoreTake queue.c:1545 (( pxQueue ))


Backtrace: 0x40378182:0x3fcebad0 0x4037fce1:0x3fcebaf0 0x403873c5:0x3fcebb10 0x40380cca:0x3fcebc40 0x4200dbcb:0x3fcebc80 0x4200e9d6:0x3fcebcb0 0x4208fc62:0x3fcebce0 0x4208ff86:0x3fcebd00 0x420913cc:0x3fcebd40 0x4200f02d:0x3fcebd80 0x4200dd9c:0x3fcebdd0 0x42048079:0x3fcebe00 0x4200c7ae:0x3fcebe30 0x4205aae6:0x3fcebe80

  #0  0x40378182:0x3fcebad0 in panic_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/panic.c:408
  #1  0x4037fce1:0x3fcebaf0 in esp_system_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/esp_system.c:137
  #2  0x403873c5:0x3fcebb10 in __assert_func at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/assert.c:85
  #3  0x40380cca:0x3fcebc40 in xQueueSemaphoreTake at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/freertos/queue.c:1549 (discriminator 1)
  #4  0x4200dbcb:0x3fcebc80 in SPIClass::beginTransaction(SPISettings) at /home/avp/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SPI/src/SPI.cpp:178
  #5  0x4200e9d6:0x3fcebcb0 in ff_sd_initialize(unsigned char) at /home/avp/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD/src/sd_diskio.cpp:473
      (inlined by) ff_sd_initialize(unsigned char) at /home/avp/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD/src/sd_diskio.cpp:502
  #6  0x4208fc62:0x3fcebce0 in ff_disk_initialize at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/fatfs/diskio/diskio.c:62
  #7  0x4208ff86:0x3fcebd00 in find_volume at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/fatfs/src/ff.c:3258
  #8  0x420913cc:0x3fcebd40 in f_mount at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/fatfs/src/ff.c:3536
  #9  0x4200f02d:0x3fcebd80 in sdcard_mount(unsigned char, char const*, unsigned char, bool) at /home/avp/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD/src/sd_diskio.cpp:800
  #10 0x4200dd9c:0x3fcebdd0 in fs::SDFS::begin(unsigned char, SPIClass&, unsigned int, char const*, unsigned char, bool) at /home/avp/.platformio/packages/framework-arduinoespressif32@3.20009.0/libraries/SD/src/SD.cpp:38
  #11 0x42048079:0x3fcebe00 in initSD() at /home/avp/pio/esp32-icenav-v3/lib/storage/storage.cpp:35
  #12 0x4200c7ae:0x3fcebe30 in setup() at /home/avp/pio/esp32-icenav-v3/src/main.cpp:92
  #13 0x4205aae6:0x3fcebe80 in loopTask(void*) at /home/avp/.platformio/packages/framework-arduinoespressif32@3.20009.0/cores/esp32/main.cpp:42
```

**Comment by hpsaturn** [comment]
Changing to this values, the core exception disappear:

```cpp
static SPIClass spiSD = SPIClass(HSPI);
static uint32_t sdFreq = 800000U;
```
On the other hand, the screen still off, but I can see that the touch detection is ready but with some issues:

```cpp
 [  2836][V][settings.cpp:317] printSettings():      GPS_tx      default 
[  2842][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FO[ 35858][E][tft.cpp:118] touchCalibrate(): Calibration not saved!
[ 36667][V][lvglSetup.cpp:171] initLVGL(): LVGL: allocating 460800 bytes PSRAM for draw buffer
[ 44676][V][tasks.cpp:25] gpsTask(): GPS Task - running on core 0
[ 44677][V][tasks.cpp:26] gpsTask(): Stack size: 6420
[ 45176][V][cli.cpp:338] initCLI(): init CLI
[ 45187][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 0 - WIFI_READY
[ 45220][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
[ 45220][D][WiFiGeneric.cpp:1035] _eventCallback(): Arduino Event: 2 - STA_START

[ 45230][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[ 45230][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[ 45234][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[ 45240][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[ 45246][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND

SSID is empty, please set a valid SSID into quotes

[ 45262][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND

░▒▓█▓▒░  ░▒▓██████▓▒░  ░▒▓████████▓▒░ ░▒▓███████▓▒░   ░▒▓██████▓▒░  ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░        ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░ 
░▒▓█▓▒░ ░▒▓█▓▒░        ░▒▓█▓▒░        ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░  ░▒▓█▓▒▒▓█▓▒░  
░▒▓█▓▒░ ░▒▓█▓▒░        ░▒▓██████▓▒░   ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓████████▓▒░  ░▒▓█▓▒▒▓█▓▒░  
░▒▓█▓▒░ ░▒▓█▓▒░        ░▒▓█▓▒░        ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░   ░▒▓█▓▓█▓▒░   
░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░        ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░   ░▒▓█▓▓█▓▒░   
░▒▓█▓▒░  ░▒▓██████▓▒░  ░▒▓████████▓▒░ ░▒▓█▓▒░░▒▓█▓▒░ ░▒▓█▓▒░░▒▓█▓▒░    ░▒▓██▓▒░    

IceNav:$ [ 45265][E][Preferences.cpp:50] begin(): nvs_open failed: NOT_FOUND
[ 45266][E][vfs_api.cpp:24] open(): File system is not mounted
[ 45269][V][renderMaps.cpp:184] generateRenderMap(): No Map Found!
[ 45310][V][renderMaps.cpp:257] generateRenderMap(): TILE: /MAP/2/2/1.png
[ 45330][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45412][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45446][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45476][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45506][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45536][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45570][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45609][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 45648][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error -1
[ 46681][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error 263
[ 47718][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error 263
[ 48762][E][Wire.cpp:499] requestFrom(): i2cWriteReadNonStop returned Error 263
```

**Comment by jgauchia** [comment]
Yes, SPI doesn't exist, HSPI or VSPI

**Comment by jgauchia** [comment]
Some fix added.
When all works I'll refactor code.
Changes are temporally

**Comment by jgauchia** [comment]
Merge to devel_lilygo_tdeck branch to start refactor code

**Pull request merged**
