### PR TITLE
Mpu9250 initial support

### PR DESCRIPTION
**Pull request by hpsaturn**

### CODE REVIEW

**Comment by jgauchia** [comment]
Checked.
Minor adjustments to the log output.

**Comment by jgauchia** [comment]
Comment about magnetic declination updated

**Comment by jgauchia** [comment]
Check this link:
[https://github.com/kriswiner/MPU9250/tree/master/AK8963_as_slave](url)

Uses a function than fuses acceleration, rotation rate, and magnetic moments to produce a quaternion-based estimate of absolute device orientation -- which can be converted to yaw, pitch, and roll

`MadgwickQuaternionUpdate(-ax, +ay, +az, gx*pi/180.0f, -gy*pi/180.0f, -gz*pi/180.0f,  my,  -mx, mz);`

a -> acceleration values
g-> gyro values
m-> magnetometer values

It's seems to return an array (q[])

And with this code it's seems to calculate yaw (heading)?

`    a12 =   2.0f * (q[1] * q[2] + q[0] * q[3]);
    a22 =   q[0] * q[0] + q[1] * q[1] - q[2] * q[2] - q[3] * q[3];
    a31 =   2.0f * (q[0] * q[1] + q[2] * q[3]);
    a32 =   2.0f * (q[1] * q[3] - q[0] * q[2]);
    a33 =   q[0] * q[0] - q[1] * q[1] - q[2] * q[2] + q[3] * q[3];
    pitch = -asinf(a32);
    roll  = atan2f(a31, a33);
    yaw   = atan2f(a12, a22);
    pitch *= 180.0f / pi;
    yaw   *= 180.0f / pi; 
    yaw   += 13.8f; // Declination at Danville, California is 13 degrees 48 minutes and 47 seconds on 2014-04-04
    if(yaw < 0) yaw   += 360.0f; // Ensure yaw stays between 0 and 360
    roll  *= 180.0f / pi;
    lin_ax = ax + a31;
    lin_ay = ay + a32;
    lin_az = az - a33;`

**Comment by hpsaturn** [comment]
Thanks! I will try it tomorrow :)

**Pull request merged**
